Repository cloud-native-toolkit/operator-masauto, pull requests merged in 2023-04, with the labels that each got.

#146 Updates for MAS 8.10 and automation to latest 12.16.1 of mas-devops
  Makefile
  README.md
  bundle/manifests/masauto-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/masauto-operator.clusterserviceversion.yaml
  config/samples/sample_appcon_cr.yaml
  config/samples/sample_assist_cr.yaml
  config/samples/sample_core_cr.yaml
  config/samples/sample_cp4d_cr.yaml
  config/samples/sample_cp4d_wsl_cr.yaml
  config/samples/sample_hpu_cr.yaml
  config/samples/sample_iot_cr.yaml
  config/samples/sample_manage_cr.yaml
  config/samples/sample_manage_external_db_cr.yaml
  config/samples/sample_monitor_cr.yaml
  config/samples/sample_optimizer_cr.yaml
  config/samples/sample_predict_cr.yaml
  docs/advanced.md
  playbooks/appcon.yml
  playbooks/assist.yml
  playbooks/core.yml
  playbooks/cp4d.yml
  playbooks/hpu.yml
  playbooks/iot.yml
  playbooks/manage.yml
  playbooks/monitor.yml
  playbooks/optimizer.yml
  playbooks/predict.yml
  requirements.yml
  samples/sample_appcon_cr.yaml
  samples/sample_assist_cr.yaml
  samples/sample_core_cis_cr.yaml
  samples/sample_core_cloudflare_cr.yaml
  samples/sample_core_cr.yaml
  samples/sample_cp4d_ai_cr.yaml
  samples/sample_cp4d_cr.yaml
  samples/sample_cp4d_platform_cr.yaml
  samples/sample_cp4d_spark_cr.yaml
  samples/sample_cp4d_spss_cr.yaml
  samples/sample_cp4d_wml_cr.yaml
  samples/sample_cp4d_wsl_cr.yaml
  samples/sample_hpu_cr.yaml
  samples/sample_iot_cr.yaml
  samples/sample_manage_cr.yaml
  samples/sample_manage_external_db_cr.yaml
  samples/sample_monitor_cr.yaml
  samples/sample_optimizer_cr.yaml
  samples/sample_predict_cr.yaml
  tasks/preinstall_check.yml
  tasks/preinstall_check_appcon.yml
  tasks/preinstall_check_assist.yml
  tasks/preinstall_check_core.yml
  tasks/preinstall_check_cp4d.yml
  tasks/preinstall_check_hpu.yml
  tasks/preinstall_check_iot.yml
  tasks/preinstall_check_manage.yml
  tasks/preinstall_check_monitor.yml
  tasks/preinstall_check_optimizer.yml
  tasks/preinstall_check_predict.yml
Labels: enhancement, minor

#156 Add helm charts for the catalog, operator, MAS Core and MAS Manage
  .github/workflows/release-charts.yml
  charts/ecosystem-engineering-catalog/.helmignore
  charts/ecosystem-engineering-catalog/Chart.yaml
  charts/ecosystem-engineering-catalog/README.md
  charts/ecosystem-engineering-catalog/templates/_helpers.tpl
  charts/ecosystem-engineering-catalog/templates/catalog-source.yaml
  charts/ecosystem-engineering-catalog/values.yaml
  charts/mas-core/.helmignore
  charts/mas-core/Chart.yaml
  charts/mas-core/README.md
  charts/mas-core/scripts/_update-configmap.sh
  charts/mas-core/scripts/copy-secret.sh
  charts/mas-core/scripts/helper-functions.sh
  charts/mas-core/support/configmap.snippet.yaml
  charts/mas-core/templates/_helpers.tpl
  charts/mas-core/templates/configmap.yaml
  charts/mas-core/templates/core.yaml
  charts/mas-core/templates/license-job.yaml
  charts/mas-core/templates/license-secret.yaml
  charts/mas-core/templates/serviceaccount.yaml
  charts/mas-core/values.yaml
  charts/mas-manage/.helmignore
  charts/mas-manage/Chart.yaml
  charts/mas-manage/templates/_helpers.tpl
  charts/mas-manage/templates/mas-manage.yaml
  charts/mas-manage/values.yaml
  charts/masauto-operator/.helmignore
  charts/masauto-operator/Chart.yaml
  charts/masauto-operator/README.md
  charts/masauto-operator/templates/_helpers.tpl
  charts/masauto-operator/templates/ibm-entitlement-secret.yaml
  charts/masauto-operator/templates/namespace.yaml
  charts/masauto-operator/templates/operator-group.yaml
  charts/masauto-operator/templates/subscription.yaml
  charts/masauto-operator/values.yaml
  charts/values_mas_core.yaml
  charts/values_mas_core_cloudflare.yaml
  charts/values_mas_core_license.yaml
  charts/values_mas_manage.yaml
  charts/values_mas_manage_external_db.yaml
  samples/sample_catalog_source.yaml
  samples/sample_core_cloudflare_cr.yaml
  samples/sample_core_cr.yaml
  samples/sample_core_license_cr.yaml
  samples/sample_manage_cr.yaml
  samples/sample_manage_external_db_cr.yaml
  samples/sample_operator_subscription.yaml
  samples/sample_operator_subscription_all.yaml
  scripts/generate-samples.sh
Labels: patch

#162 Update helm release process to streamline dependencies
  .github/workflows/helm-publish.yaml
  .github/workflows/release-charts.yml
Labels: bug, patch

#168 Updates version to latest automation 13.4.0
  Makefile
  README.md
  bundle/manifests/masauto-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  requirements.yml
Labels: enhancement, minor
